### ISSUE TITLE
cassandra nodes refuse to come up. Seed provider couldn't lookup host cassandra-0.cassandra.jaeger.svc.cluster.local

### ISSUE THREAD

**Issue by Dieterbe** [jaegertracing/jaeger-kubernetes#33]
when i try to use the production template, I always get this:
```
~ ❯❯❯ kubej get po
NAME                               READY     STATUS             RESTARTS   AGE
cassandra-0                        1/1       Running            0          4m
cassandra-1                        0/1       CrashLoopBackOff   5          4m
cassandra-2                        0/1       CrashLoopBackOff   5          3m
```

cassandra-0 logs
```
INFO  [main] 2017-09-13 14:06:29,146 StorageService.java:857 - This node will not auto bootstrap because it is configured to be a seed node.
```
and starts up fine.

the other two log:
```
INFO  [main] 2017-09-13 14:09:32,907 DatabaseDescriptor.java:710 - Back-pressure is disabled with strategy org.apache.cassandra.net.RateBasedBackPressure{high_ratio=0.9, factor=5, flow=FAST}.
INFO  [main] 2017-09-13 14:09:33,134 GossipingPropertyFileSnitch.java:64 - Loaded cassandra-topology.properties for compatibility
WARN  [main] 2017-09-13 14:09:33,155 SimpleSeedProvider.java:60 - Seed provider couldn't lookup host cassandra-0.cassandra.jaeger.svc.cluster.local
Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: The seed provider lists no seeds.
ERROR [main] 2017-09-13 14:09:33,158 CassandraDaemon.java:706 - Exception encountered during startup: The seed provider lists no seeds.
The seed provider lists no seeds.
```

note that the statefulset defines:
```
        - name: CASSANDRA_SEEDS
          value: cassandra-0.cassandra.jaeger.svc.cluster.local
```
i've tried some others like `cassandra-0` with same result.
I'll try some more.
i'm pretty sure at one point i was able to exec into one of the other containers before it shut down, and a ping to cassandra-0.cassandra.jaeger.svc.cluster.local worked fine. so i'm puzzled

**Comment by Dieterbe** [comment]
interestingly, this used to work at some point. i wonder if it's due to our k8s being upgraded recently. (we're now on v1.6.9)

**Comment by Dieterbe** [comment]
this could have been caused by me changing the clusterIP setting to get an ip, instead of leaving it as `None`.  per the docs - https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/ - a headless service is required, so this looks like PEBKAC

**Comment by kumarganesh2814** [comment]
@Dieterbe 

Hi 

I am also trying to deploy casandra cluster on my kube cluster running on centos VM with 2 worker and 1 master 

But always second need keep failing with below error any idea

``WARN  17:50:21 No host ID found, created 7ffe85b4-eef6-4274-9461-821d538c1181 (Note: This should happen exactly once per node).
Exception (java.lang.RuntimeException) encountered during startup: Unable to gossip with any seeds
java.lang.RuntimeException: Unable to gossip with any seeds
        at org.apache.cassandra.gms.Gossiper.doShadowRound(Gossiper.java:1386)
        at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:484)
        at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:778)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:648)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:548)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:385)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601)
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:730)
ERROR 17:50:53 Exception encountered during startup
java.lang.RuntimeException: Unable to gossip with any seeds
        at org.apache.cassandra.gms.Gossiper.doShadowRound(Gossiper.java:1386) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:484) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:778) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:648) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:548) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:385) [apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601) [apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:730) [apache-cassandra-3.9.jar:3.9]
WARN  17:50:53 No local state or state is in silent shutdown, not announcing shutdown
``

**Comment by Icedroid** [comment]
meet the same problem:
`
WARN  [main] 2019-10-17 06:00:47,228 DatabaseDescriptor.java:474 - Small commitlog volume detected at /var/lib/cassandra/commitlog; setting commitlog_total_space_in_mb to 2142.  You can override this in cassandra.yaml
WARN  [main] 2019-10-17 06:00:47,229 DatabaseDescriptor.java:501 - Small cdc volume detected at /var/lib/cassandra/cdc_raw; setting cdc_total_space_in_mb to 1071.  You can override this in cassandra.yaml
WARN  [main] 2019-10-17 06:00:56,730 DatabaseDescriptor.java:550 - Only 2.094GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
INFO  [main] 2019-10-17 06:00:58,936 RateBasedBackPressure.java:123 - Initialized back-pressure with high ratio: 0.9, factor: 5, flow: FAST, window size: 2000.
INFO  [main] 2019-10-17 06:00:59,027 DatabaseDescriptor.java:729 - Back-pressure is disabled with strategy org.apache.cassandra.net.RateBasedBackPressure{high_ratio=0.9, factor=5, flow=FAST}.
INFO  [main] 2019-10-17 06:01:10,432 GossipingPropertyFileSnitch.java:64 - Loaded cassandra-topology.properties for compatibility
WARN  [main] 2019-10-17 06:01:12,730 SimpleSeedProvider.java:60 - Seed provider couldn't lookup host jaeger-cassandra-0.jaeger-cassandra.common-system.svc.cluster.local
Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: The seed provider lists no seeds.
ERROR [main] 2019-10-17 06:01:12,828 CassandraDaemon.java:708 - Exception encountered during startup: The seed provider lists no seeds.
The seed provider lists no seeds.
`
