### ISSUE TITLE
Exception (org.apache.cassandra.io.FSReadError) encountered during startup: java.io.EOFException

### ISSUE THREAD

**Issue by Dieterbe** [jaegertracing/jaeger-kubernetes#35]
Hello folks,
I know this is not really a jaeger question per se, but i have a problem sometimes with cassandra when i deploy the production template from this repo, maybe someone knows an answer.

basically typically the whole jaeger setup (incl cassandra) runs fine for a while, and then suddenly the cassandra container starts crashlooping with this error:
```
Exception (org.apache.cassandra.io.FSReadError) encountered during startup: java.io.EOFException
FSReadError in /var/lib/cassandra/hints/718a84bd-5f5c-4ca2-b4c6-93774ef9876c-1506428454916-1.hints
	at org.apache.cassandra.hints.HintsDescriptor.readFromFile(HintsDescriptor.java:235)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.cassandra.hints.HintsCatalog.load(HintsCatalog.java:65)
	at org.apache.cassandra.hints.HintsService.<init>(HintsService.java:97)
	at org.apache.cassandra.hints.HintsService.<init>(HintsService.java:88)
	at org.apache.cassandra.hints.HintsService.<clinit>(HintsService.java:66)
	at org.apache.cassandra.service.StorageProxy.<clinit>(StorageProxy.java:127)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:627)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:612)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:393)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:600)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:689)
Caused by: java.io.EOFException
	at java.io.RandomAccessFile.readInt(RandomAccessFile.java:803)
	at org.apache.cassandra.hints.HintsDescriptor.deserialize(HintsDescriptor.java:344)
	at org.apache.cassandra.hints.HintsDescriptor.readFromFile(HintsDescriptor.java:231)
	... 21 more
```

it seems to be preceeded by:
```
INFO  [pool-3-thread-1] 2017-09-26 14:48:41,871 AutoSavingCache.java:262 - Harmless error reading saved cache /var/lib/cassandra/saved_caches/KeyCache-e.db
java.io.UTFDataFormatException: malformed input around byte 1
	at java.io.DataInputStream.readUTF(DataInputStream.java:656) ~[na:1.8.0_131]
	at java.io.DataInputStream.readUTF(DataInputStream.java:564) ~[na:1.8.0_131]
	at org.apache.cassandra.cache.AutoSavingCache.loadSaved(AutoSavingCache.java:215) ~[apache-cassandra-3.11.0.jar:3.11.0]
	at org.apache.cassandra.cache.AutoSavingCache$3.call(AutoSavingCache.java:164) [apache-cassandra-3.11.0.jar:3.11.0]
	at org.apache.cassandra.cache.AutoSavingCache$3.call(AutoSavingCache.java:160) [apache-cassandra-3.11.0.jar:3.11.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
INFO  [pool-3-thread-1] 2017-09-26 14:48:41,871 AutoSavingCache.java:173 - Completed loading (19 ms; 275 keys) KeyCache cache
```

disk has not run full and i also don't see any io errors in `dmesg`

**Comment by jpkrohling** [comment]
@burmanm , have you seen this before?

**Comment by burmanm** [comment]
@Dieterbe Can you give some details of the file? Or even the whole file? How many nodes do you have deployed in this case and what happens to them to while hints file is being generated?

The preceding error does not seem to be related at all.

**Comment by burmanm** [comment]
I'll fix my comment slightly, the preceding error is not directly related to hints file (two quite different things), but obviously both are showing errors in the I/O. That is, both are unable to read the first byte of a file from the disk. Probably more likely the environment than Cassandra bug.

**Comment by pavolloffay** [comment]
@Dieterbe did you manage to solve it? I will close it per @burmanm response. Feel free to re-open.

**Comment by Dieterbe** [comment]
thanks for the help guys. incidentally we're in the process of moving our jaeger stack to a different cloud hosting provider, maybe that will stop this from happening.

(for the record, i don't have the file anymore, we have 3 nodes as per the standard production template from this repo that we use, and not sure what happened to them while hints file is being generated)
